### ISSUE TITLE
Donation link

### ISSUE THREAD

**Issue by CHJ85** [SartoxSoftware/audacium#30]
Hi there. Great work on this fork. I love that you're so persistent on this project.
But I had an idea that'll encourage you to continue.
You should put a donation link inside Audacium, in the Help menu as well as the splash screen.
It should be a payment service that allows both crypto, paypal and credit card, like Stripe or Skrill.

**Comment by AnErrupTion** [comment]
I have a Liberapay page where people can donate with PayPal, or at the bottom of the README I have a Bitcoin and Monero wallet address.

**Comment by CHJ85** [comment]
Right. But further down the line, it might be a good idea to put those links somewhere in the app itself, because most people don't go to github unless the software isn't available in their package manager / software center. And I'm sure once this fork gets off the ground, you'd like for it to become available in the distros repositories.

**Comment by SnowmanKing** [comment]
Definitely agree.

**Comment by Camology** [comment]
This is the one I meant to comment on, no need since it is on the website. 

Donations

You can donate to me via PayPal using the Sponsor button on GitHub and going to my Liberapay page, or support me via Bitcoin or Monero :

Bitcoin : bc1qz6f2gu8f2vr8knyt8y76jxc8h7an93695kyyj0
Monero : 4834cgrEKBgbYVugTxHzZPJqyDXBBhreNF4CxauZCbLAQfrzeFuRifE4Pwy6uAH3t61rLwe89XF3v775qfuRzr8mRHzuZfk

**Comment by AnErrupTion** [comment]
Donate to me via Litecoin now, as I currently control that wallet (lost control of the 2 other ones)
